### ISSUE TITLE
Empty answer to `type: str` text question without default value is `None` but should be `""`

### ISSUE THREAD

**Issue by sisp** [copier-org/copier#956] opened 2023-02-08 19:36 UTC
**Describe the problem**

The result of an empty answer to a `type: str` text question without a default value is `None`. This behavior is unexpected and inconsistent with the behavior other (text input) questions.

**Template**

```yaml
string_question:
  type: str
```

*Note:* If a default value is set

```yaml
string_question:
  type: str
  default: the default value
```

then the result of an empty answer is `""`.

**To Reproduce**

1. Run `copier /path/to/template /path/to/project`
2. Answer nothing, i.e. just press "Enter".
3. See the content of `.copier-answers.yml`:

    ```yaml
    _src_path: /path/to/template
    string_question: null
    ```
4. If you add a `.jinja` file to the template with content like

    ```
    answer: {% if string_question == None %}None{% else %}"{{ string_question }}"{% endif %}
    ```

    then the content of the rendered file will be:

    ```
    answer: None
    ```

**Expected behavior**

An empty answer should result in an empty string `""`.

**Environment**
 - OS: Ubuntu 20.04
 - Copier version: `copier 7.0.1`
 - Python version: 3.9.13
 - Installation method: pipx+pypi

**Additional context**

I think the current behavior is incorrect for several reasons:
1. It is inconsistent with other question types (`int` and `float`) where an empty answer is not accepted with an error `Invalid input`.
2. It is inconsistent with all other question types that have no answer value with the semantics of "not answered" (if that's the intention of `None` for `type: str` questions).
3. It is inconsistent with a `type: str` question that has a default value as the result of an empty answer is `""` and not `None`.
4. It is not possible to answer a `type: str` question with an empty string which may be a perfectly valid answer.

**Comment by sisp** [comment] 2023-02-09 19:54
I think this issue also questions the definition of the `-l, --default` flag

```
-l, --defaults                     Use default answers to questions, which might be null if not specified.
```

along with Copier's current behavior when the no default answer is available and the value is `null`. This behavior is inconsistent with with the interactive questionnaire where it isn't possible to provide a `null` answer, i.e. questions without a default value *must* be answered. The way I see it, the `-l, --default` flag only makes sense to use when _all_ questions have default answers, and when it is used while some questions don't have default answers then Copier should raise an error.

WDYT, @yajo?

**Comment by sisp** [comment] 2023-02-09 20:40
If a default value was required (which is the case for the short question syntax), then this problem would be solved, too. But requiring default values would be a breaking change, and there might not always be natural default values.

**Comment by yajo** [comment] 2023-02-10 06:02
Thanks for the detailed report! 

This is a known issue, please follow up there.

Duplicate of #355

**Closed by yajo** 2023-02-10 06:02 UTC
Labels: bug
