### ISSUE TITLE
Non-prompted values

### ISSUE THREAD

**Issue by pawamoy** [copier-org/copier#229] opened 2020-07-13 15:43 UTC
In my templates I often duplicate code to build a string based on the user's answers. I would like to avoid duplicating this code and instead populate a variable once, in `copier.yml` using a non-prompted value. The user must not change this value, I'd like to always use the default. Something like this maybe?

```yaml
gitlab_namespace:
  type: str

repository_name:
  type: str

# here
namespace_id:
  type: str
  prompt: no
  default: "[% if gitlab_namespace.count('/') %]r-[% else %]p-[% endif %][[ gitlab_namespace.split('/')[-1] ]]"

# then I could populate other variables as well, these are just examples
docker_image:
  type: str
  prompt: no
  default: "[[ namespace_id ]]/[[ repository_name ]]-docker"

package_distribution_name:
  type: str
  prompt: no
  default: "[[ namespace_id ]]-[[ repository_name ]]"
```

There surely are other ways than introducing a new `prompt` key to do this though, like injecting data in the context from a special `_context` list or a pre-generation hook (like a Python script modifying and returning the context dict). Maybe there's a way to play with Jinja2's `extends`, `include`, `macro`, `with` or `set` capabilities as well 🙂

**Comment by pawamoy** [comment] 2020-07-17 16:07
I tried many things using only Jinja2 capabilities, but was not able to get it to work.

I think the easiest thing to implement would be a new `_extra_context` option. It feels consistent, and could reuse code.

```yaml
gitlab_namespace:
  type: str

repository_name:
  type: str

_extra_context:
  - namespace_id: "[% if gitlab_namespace.count('/') %]r-[% else %]p-[% endif %][[ gitlab_namespace.split('/')[-1] ]]"
  - docker_image: "[[ namespace_id ]]/[[ repository_name ]]-docker"
  - package_distribution_name: "[[ namespace_id ]]-[[ repository_name ]]"
```

Each item in extra context would then be rendered using the same method we use to render prompt values. We could also consider adding an `--extra-context` CLI option, and `extra_context` API option, allowing users to inject even more, or override item in `_extra_context`, and that would cover 95% of use-cases.

What do you think?

**Comment by Yajo** [comment] 2020-07-21 06:37
Humm honestly this sounds like a bit of feature creep to me... :thinking: 

Have you tried storing those definitions as [macros in a file](https://jinja.palletsprojects.com/en/2.11.x/templates/#macros) and then [importing](https://jinja.palletsprojects.com/en/2.11.x/templates/#import) it?

**Comment by pawamoy** [comment] 2020-07-21 07:29
In fact I got it working, but it's bit ugly 🙂 

I added a `context` file in the template. It uses Jinja2 `set` instructions to declare some variables. It looks like this:

```jinja2
[#- Initiate context with a copy of Copier answers -#]
[%- set ctx = _copier_answers.copy() -%]

[#- Populate our new variables -#]
[%- set _ = ctx.update({"namespace_id": ("r-" if gitlab_namespace.count("/") else "p-") + ctx.gitlab_namespace.split("/")[-1] }) -%]
[%- set _ = ctx.update({"docker_image": ctx.namespace_id + "/" + ctx.repository_name_docker}) -%]
```

**Why am I using a `ctx` dictionary instead of plain variables?** Because then I can import the `ctx` object in other templates:

```jinja2
[%- from "projet/context" import ctx with context -%]
```

...but also because I don't want my variables to be split between top scope (`[[ a_copier_answer ]]`) and dict-scope (`[[ ctx.added_variable ]]`). It could become hard to remember which one is where when writing/maintaining lots of templates.

- Don't forget to use a relative path from the root of the repository, not the subdirectory option: `project/context`
- Don't forget to import with the current context, so `_copier_answers` is available in the `context` template
- Don't name the file `context.jinja` (or `context.tmpl` depending on your chosen suffix), you don't want to render it (it would become empty) before other templates import it

**Why am I using a copy of `_copier_answers` and a direct reference?** Because otherwise the variables I add would end up in the `.copier-answers.yml` file as well.

**What is this ugly `[%- set _ = ctx.update({"onekey": "onevalue"}) -%]` thing?**

This is the most elegant way to update a dictionary without the [*Expression Statement*](https://jinja.palletsprojects.com/en/2.11.x/extensions/#expression-statement) extension loaded in the Jinja environment. Since I'm building variables incrementally, I cannot set them all at once with one `set _ = ctx.update({all_keys: all_vars})` instruction.

Took me a day to workout all this 😄 

**Why is it not optimal?**

- Because you have to import the `ctx` object in every template
- Because you have to access all variables with `[[ ctx.var ]]` to keep consistent, and therefore have to update all templates (a quick sed does the work though)
- Because you have to add a post-generation task that deletes this `context` file, which is useless once the projet is generated

**Comment by Yajo** [comment] 2020-07-21 09:45
Humm but that's not what I asked. Check this out:

```bash
➤ tree
.
└── tpl
    ├── copier.yml
    ├── macros.tmpl
    └── result.yml.tmpl

1 directory, 3 files

➤ cat tpl/copier.yml 
_exclude:
  - /macros
  - /copier.yml

gitlab_namespace:
  type: str
  default: copier-org

repository_name:
  type: str
  default: copier

➤ cat tpl/macros.tmpl 
[%- macro namespace_id() %]
  [%- if gitlab_namespace.count('/') %]r-[% else %]p-[% endif %][[ gitlab_namespace.split('/')[-1] ]]
[%- endmacro %]

[%- macro docker_image() %]
  [[- namespace_id() ]]/[[ repository_name ]]-docker
[%- endmacro %]

[%- macro package_distribution_name() %]
  [[- namespace_id() ]]-[[ repository_name ]]
[%- endmacro %]

➤ cat tpl/result.yml.tmpl 
[%- import 'macros.tmpl' as macros with context -%]
gitlab_namespace: [[gitlab_namespace]]
repository_name: [[repository_name]]
namespace_id: [[macros.namespace_id()]]
docker_image: [[macros.docker_image()]]
package_distribution_name: [[macros.package_distribution_name()]]

➤ copier -f copy tpl dst

    create  result.yml



➤ tree
.
├── dst
│   └── result.yml
└── tpl
    ├── copier.yml
    ├── macros.tmpl
    └── result.yml.tmpl

2 directories, 4 files

➤ cat dst/result.yml 
gitlab_namespace: copier-org
repository_name: copier
namespace_id: p-copier-org
docker_image: p-copier-org/copier-docker
package_distribution_name: p-copier-org-copier
```

You can even add parameters to macros if you don't want to import them `with context`, and you can also do `[% from 'macros.tmpl' import docker_image %]` if you prefer to not use the `macros.` namespace or just want one of the macros.

TBH this seems pretty clean and maintainable to me... :shrug:

**Comment by pawamoy** [comment] 2020-07-21 11:03
Indeed, clean and readable! Thanks. But it presents the same inconveniences as my solution:

- mixed access: `[[ var1 ]]` and `[[ macros.var2() ]]` (with extra parentheses!), unless we directly import the macros without namespace, which doesn't sound better
- having to import in each template

Anyway, thank you very much for taking the time to read and reply 🙂 

I think this is just one more issue in favor of a way to modify the Jinja env (#208, #182)

**Comment by Yajo** [comment] 2020-07-22 06:52
Those problems are not big deals IMHO. I am used to importing other functions from other modules in Python and that sounds natural to me. Actually, being explicit on why things work is good, thinking about maintenance (not just Copier, but also downstream templates).

About parenthesis, actually they seem good to me also. If you're all the time reusing the same macros (slugify could be one of those), you can have a separate git repository with macros that you include as a submodule in your other templates (remember Copier supports git submodules). Then, it would make more sense to use macro arguments, since the context can easily differ on each template. Maintainability isn't always about saving keystrokes! :blush: 

Well, as I think we agree this is a good solution, let me close this. Thanks!

**Closed by Yajo** 2020-07-22 06:52 UTC

**Comment by pawamoy** [comment] 2020-08-03 09:32
Actually I just found a use-case that cannot be solved with the above solutions: using an extra value in the name of a file/directory.
Unless you can name a file `[%- from "project/context" import ctx with context -%][[ ctx.some_extra_value ]].md.jinja`?

**Comment by Yajo** [comment] 2020-08-03 12:05
Before guessing, the best would be to have a real world case, where we can see exactly what fails. Maybe a simpler solution would be to avoid using `render_string` if possible. :shrug: 

Do you have a reproducible example?

**Comment by pawamoy** [comment] 2020-09-24 13:52
I forgot to report back. It actually works. Filename are horribly long and difficult to read, but it works. The "context" file also *must* be placed at the root of the template, because slashes are not allowed in filenames.

**Comment by Broele** [comment] 2023-09-22 10:11
> Actually I just found a use-case that cannot be solved with the above solutions: using an extra value in the name of a file/directory. Unless you can name a file `[%- from "project/context" import ctx with context -%][[ ctx.some_extra_value ]].md.jinja`? I doubt so because first, there's a slash in the name and second, the name is rendered with `render_string` so I'm not sure the `import` mechanisms work here.

It has been a while, but I would like to report, that one can beautify these such file / folder names a bit by creating one file for each file / folder that renders the actual name ind using `include` instead of `import`. This would reduce aboves example to 
```
[% include 'some_extra_value_file' %].md.jinja
```

> I forgot to report back. It actually works. Filename are horribly long and difficult to read, but it works. The "context" file also _must_ be placed at the root of the template, because slashes are not allowed in filenames.

Of course this is only reasonable, if there are not many of such files, since all would populate the root-folder.

__Note__: with the current default settings, it would be `{% ... %}` instead `[% ... %]`

**Comment by guillaumep** [comment] 2023-11-20 19:33
To those finding this issue through a Web search: this feature can be now implemented by using a computed value, as such:

```yaml
some_var:
  type: str
  default: "{{referenced_var1}} {{referenced_var2}}"
  when: false
```

See documentation: https://copier.readthedocs.io/en/stable/configuring/#advanced-prompt-formatting
