### ISSUE TITLE
Tasks don't run inside newly created project folder

### ISSUE THREAD

**Issue by gotofritz** [copier-org/copier#1034] opened 2023-03-10 00:37 UTC
**Describe the problem**
I create a project, then I want a task to cd into the newly created projects and do things, such as `git init`, `pnpm install`.
Instead those commands run in the folder where I originally called copier. Using cd doesn't help, unless I prepend each individual command with it

```yaml
_tasks:
  - "echo '1:' && pwd"
  - "cd /put/it/{{project_name}}"
  - "echo '2:' && pwd"
  - "cd /put/it/{{project_name}} && echo '3:' && pwd"
```

where project_name = 'there'

```bash
> cd i/am/here
> copier mytemplate/ put/it/
> Running task 1 of 4: echo '1:' && pwd
1:
 i/am/here
 > Running task 2 of 4: cd put/it/there
 > Running task 3 of 4: echo '2:' && pwd
2:
 i/am/here
 > Running task 4 of 4: cd there && echo '3:' && pwd
3:
/put/it/there
```

**Template**
see ☝️

**To Reproduce**

see ☝️

**Logs**
it doesn't error, it just does the wrong thing

**Environment**
 - OS: X
 - Copier version: copier 7.0.1
 - Python version: 3.11.1
 - Installation method: pip +pypi

**Comment by sisp** [comment] 2023-03-11 14:33
I cannot reproduce the problem on Ubuntu 20.04 with the same Copier and Python versions you've stated, it works as expected for me. This behavior is also tested and the last change to this test file was before the release of v7.0.1:

https://github.com/copier-org/copier/blob/91966047d9741099b4925612c5c0c3a0dbe2490c/tests/test_tasks.py#L23-L27

https://github.com/copier-org/copier/blob/91966047d9741099b4925612c5c0c3a0dbe2490c/tests/test_tasks.py#L34-L36

https://github.com/copier-org/copier/blob/91966047d9741099b4925612c5c0c3a0dbe2490c/tests/test_tasks.py#L39-L45

I've also tried it with Copier v7.1.0a0 and v6.2.0 and both work fine. Can you double-check please?

**Comment by yajo** [comment] 2023-03-29 17:53
I also tested it with current master and I cannot reproduce. As @sisp said, this is a tested case. There must be something else that makes it fail. Closing.

**Closed by yajo** 2023-03-29 17:53 UTC
Labels: bug
