### ISSUE TITLE
Validator support on prompt using choices

### ISSUE THREAD

**Issue by verdaatt** [copier-org/copier#996] opened 2023-02-21 22:18 UTC
**Is your feature request related to a problem? Please describe.**

Input validation is supported on prompts that do not use the `choices` option. There are however valid reasons for wanting to use the validator feature to validate if the chosen option from the choices list is compatible with inputs on other prompts. An example is these prompts for inputting Terraform and Terragrunt versions, where there's a Terraform version compatibility matrix for Terragrunt that we'd like to enforce using the validator:

```yaml
terraform_version:
  type: str
  default: "1.3.9"
  help: Which Terraform version do you want to use?
  choices:
    "1.3": "1.3.9"
    "1.2": "1.2.9"
    "1.1": "1.1.9"
    "1.0": "1.0.11"
    "0.15": "0.15.5"
    "0.14": "0.14.11"
    "0.13": "0.13.7"

terragrunt_version:
  type: str
  default: "0.43.2"
  help: |
    Which Terragrunt version you want to use?

    When choosing a previous version, please be mindful of Terraform version compatibility: https://terragrunt.gruntwork.io/docs/getting-started/supported-terraform-versions/
  choices:
    - "0.43.2"
    - "0.42.8"
    - "0.41.0"
    - "0.40.2"
    - "0.39.2"
    - "0.38.12"
    - "0.37.4"
    - "0.36.12"
    - "0.35.20"
    - "0.34.3"
    - "0.33.2"
    - "0.32.6"
    - "0.31.11"
    - "0.30.7"
    - "0.29.10"
    - "0.28.24"
    - "0.27.4"
    - "0.26.7"
    - "0.25.5"
  # Validator implements https://terragrunt.gruntwork.io/docs/getting-started/supported-terraform-versions/
  validator: >-
    {% if (terraform_version | regex_search('^1\.3\..*$')) %}
      {% if not (terragrunt_version | regex_search('^0\.(4\d|[5-9]\d).*$')) %}
      This version is not compatible with the Terraform 1.3.x, Please use version >= 0.40.0
      {% endif %}
    {% elif (terraform_version | regex_search('^1\.2\..*$')) %}
      {% if not (terragrunt_version | regex_search('^0\.(3[89]|[4-9]\d).*$')) %}
      This version is not compatible with the Terraform 1.2.x, Please use version >= 0.38.0
      {% endif %}
    {% elif (terraform_version | regex_search('^1\.1\..*$')) %}
      {% if not (terragrunt_version | regex_search('^0\.(3[6-9]|[4-9]\d).*$')) %}
      This version is not compatible with the Terraform 1.1.x, Please use version >= 0.36.0
      {% endif %}
    {% elif (terraform_version | regex_search('^1\.0\..*$')) %}
      {% if not (terragrunt_version | regex_search('^0\.(3[1-9]|[4-9]\d).*$')) %}
      This version is not compatible with the Terraform 1.0.x, Please use version >= 0.31.0
      {% endif %}
    {% elif (terraform_version | regex_search('^0\.15\..*$')) %}
      {% if not (terragrunt_version | regex_search('^0\.(29|[3-9]\d).*$')) %}
      This version is not compatible with the Terraform 0.15.x, Please use version >= 0.29.0
      {% endif %}
    {% elif (terraform_version | regex_search('^0\.14\..*$')) %}
      {% if not (terragrunt_version | regex_search('^0\.(2[7-9]|[3-9]\d).*$')) %}
      This version is not compatible with the Terraform 0.14.x, Please use version >= 0.27.0
      {% endif %}
    {% elif (terraform_version | regex_search('^0\.13\..*$')) %}
      {% if not (terragrunt_version | regex_search('^0\.(2[5-9]|[3-9]\d).*$')) %}
      This version is not compatible with the Terraform 0.13.x, Please use version >= 0.25.0
      {% endif %}
    {% endif %}
```

**Describe the solution you'd like**

Always support validator functionality for a prompt, so also when choices are provided.

**Describe alternatives you've considered**

Using a simple input instead of choices, which is much more error prone and would require much more validation to enforce the allowed values currently defined in choices. This is not really user friendly.

**Additional context**

**Comment by sisp** [comment] 2023-02-22 10:08
I think the UX would be better if incompatible choices weren't listed at all instead of showing an error. I believe Copier doesn't support this at the moment because Jinja syntax cannot be used outside/around a choice value to make it conditional.

WDYT, @yajo?

**Comment by verdaatt** [comment] 2023-02-22 12:16
Agree, that would be even more user-friendly but I assume that's an even more complicated feature to develop. Besides that I assume there are other valid use cases out there for using validator in combination with choices so I guess one does not exclude the other. We might have to break out your suggestion into a separate ticket?

**Comment by sisp** [comment] 2023-02-23 10:38
> [...] but I assume that's an even more complicated feature to develop.

It might be actually be quite simple. I've created a separate issue to discuss the idea of conditional choices: #1001.

> Besides that I assume there are other valid use cases out there for using validator in combination with choices [...]

Would you mind elaborating? I'm having a hard time thinking of a use case where choice validation is better than omitting invalid choices.

**Comment by yajo** [comment] 2023-03-10 21:23
Is there choices validation support in the upstream library we use? 🤔

**Comment by yajo** [comment] 2023-03-11 06:16
After thinking it more, this definitely seems like a duplicate of #1001. So, closing. Let us continue there.

**Closed by yajo** 2023-03-11 06:16 UTC
Labels: enhancement
