### ISSUE TITLE
feat: Leave pre-existing files unchanged

### ISSUE THREAD

**Issue by parekh0711** [copier-org/copier#429] opened 2021-07-19 14:22 UTC
**Is your feature request related to a problem? Please describe.**
If copier is generating a project at /x/y/z location, and it fails because of some reason, it removes all the files it had generated as well as the directory's pre existing contents.
This can be problematic if the directory contained files that were important. 
In my case, I misunderstood the destination argument to be the **destination directory**, and copier ended up nuking my entire parent directory. This was of course, due to my misunderstanding; but this behaviour may not be the best solution.

**Describe the solution you'd like**
Copier should not delete any directories/files that it did not create on failures.

**Comment by xsc27** [comment] 2021-07-20 02:45
is this a duplicate of #262 ?

**Comment by Yajo** [comment] 2021-07-22 14:38
Yes, thanks.

**Closed by Yajo** 2021-07-22 14:38 UTC
Labels: enhancement
