### ISSUE TITLE
Can't update project when copying from local template

### ISSUE THREAD

**Issue by slocoro** [copier-org/copier#1616] opened 2024-04-30 07:54 UTC
### Describe the problem

I created a project from a local template. I created the project using `copier copy path/to/template .` in `~/Desktop`. When I cd into my new project (`~/Desktop/project`) and run `copier update .` I get a `ValueError("Local template must be a directory.")` error.

I'm able to update the project if I change `_src_path` key in the `.copier-answers.yml` file to the absolute path to the template.

Is this expected or am I not using my local template as intended? 

Found this https://github.com/copier-org/copier/issues/335 which seems related.

### Template

local template

### Logs

raise ValueError("Local template must be a directory.")

### Expected behavior

The project should update from the template without error.

### Operating system

macOS

### Operating system distribution and version

Venture 13.5

### Copier version

9.2.0

### Python version

CPython 3.10

### Installation method

pipx+pypi

**Comment by yajo** [comment] 2024-05-14 11:01
Duplicate of #335.

**Closed by yajo** 2024-05-14 11:01 UTC
Labels: bug, triage
