### ISSUE TITLE
Overwrite is not applied during update

### ISSUE THREAD

**Issue by chris-sanders** [copier-org/copier#379] opened 2021-03-26 21:12 UTC
While testing my workflow I've found that running `copier update` doesn't overwrite the changes if the destination folder is a git repository. This testing was done on the latest 5.1.0 not the v6 development branch, although I think it does the same thing. 

After creating an initial repository and checking in the template I then modified the the tox.ini file, committed the change, and ran an updated. 

Here is the snipped where the file is recognized as changed, I confirm and it says it's been forced. However immediately after a git status shows that nothing has actually changed in the directory and if I check the file it's still the modified version.

```
  conflict  tox.ini
 Overwrite /home/chris/src/juju/charms/operators/charm-github-runner/tox.ini? [Y/n] Y
     force  tox.ini
 identical  .copier-answers.yml
    create  tasks.py
 identical  .github/
 identical  .github/workflows/
 identical  .github/workflows/tests.yaml
 identical  tests/
 identical  tests/data/
 identical  tests/data/empty
 identical  tests/unit/
 identical  tests/unit/test_charm.py
 identical  tests/unit/empty
 identical  tests/integration/
 identical  tests/integration/test_charm.py
 identical  src/
 identical  src/charm.py

 > Running task 1 of 4: invoke check-yaml
 > Running task 2 of 4: invoke charm-permissions
 > Running task 3 of 4: invoke remove-unused-files
 > Running task 4 of 4: invoke remove-tasks

chris@x1c:~/src/juju/charms/operators/charm-github-runner$ git status
On branch master
nothing to commit, working tree clean

```

Maybe I'm not understanding how updates are suppose to work, but the UI seems to say it's going to overwrite my local copy but never does.

**Comment by Yajo** [comment] 2021-03-27 07:18
This might be specific to the template, or to the state of the project prior to the update. Is it possible to read both repos? Or can you get to a minimal reproducible case?

**Comment by Yajo** [comment] 2021-03-27 07:47
I'll close it because there's nothing I can do unless I have all the info. Please reopen if you provide it. Thanks for the report 😀

**Closed by Yajo** 2021-03-27 07:47 UTC
Labels: Status:Triage
