### ISSUE TITLE
Check dir supplied to `copier` exists before going through questions

### ISSUE THREAD

**Issue by phinate** [copier-org/copier#1497] opened 2024-02-05 10:30 UTC
### Actual Situation

One may accidentally run a `copier copy` command without making a new directory first if that's desired.

### Desired Situation

I'd want the dir to be created for me, or an error message that comes up telling me the dir doesn't exist _before_ filling in the template.

### Proposed solution

Should be a pretty simple check to make, happy to open a PR for this. 

Couldn't find this issue documented anywhere, so apologies if this is already supported with a flag or asked elsewhere.

edit: after playing around, I can see that the creation behavior is what happens (but errored on a particular string if the directory is read-only, e.g. `/path/to/dir`). Happy to close this, but I'd probably like it documented somewhere fairly early in the README that this is what happens!

**Comment by pawamoy** [comment] 2024-02-05 11:53
That's pretty much implied by the first example:

> `copier copy path/to/project/template path/to/destination`

I don't think adding troubleshooting notes early in the README is a good idea, but I'm not opposed to it either. Maybe Copier could instead output a useful error message when the destination directory is read-only.

**Comment by phinate** [comment] 2024-02-05 12:07
+1 for the read-only error! You end up with a `FileNotFoundError` first if that directory doesn't exist.

regarding docs: I submitted some text in #1498 that I think should flag it minimally in the README, and a little more explicitly in the template generation page.

**Comment by yajo** [comment] 2024-02-11 13:54
I don't think this is a good idea.

In case you run copy over a preexisting dir, copier will copy on it, just like it should do.

If the dir happens to be a git-tracked template that contains an answers file, you can use copy as a recopy alternative. Sometimes an upstream template lacks some patches, then you need to use a downstream template with those patches and you need to change the origin of the template. The only official way to do that is to issue a copy command over a preexisting template.

Let me close this request because it breaks expected behaviours, just to keep the issue tracker clean. But you can keep commenting if you want 😉

**Closed by yajo** 2024-02-11 13:54 UTC
Labels: enhancement

**Comment by pawamoy** [comment] 2024-02-11 14:22
@yajo the suggestion was to handle the case where the destination directory already exists but is read-only, meaning Copier will never be able to write into it (be it for an update or a recopy). But after actually testing this out, it seems we already get a `PermissionError`, which is explicit enough I think.
