### ISSUE TITLE
`skip_if_exists` interaction with deleted files on update

### ISSUE THREAD

**Issue by lkubb** [copier-org/copier#1718] opened 2024-07-31 22:44 UTC
### Describe the problem

When a path that is affected by `skip_if_exists` is deleted in a generated project, an update regenerates it anyways.

### Template

https://github.com/salt-extensions/salt-extension-copier (sadly requires `--trust`, but this could be reproduced easily with a simple demo template)

### To Reproduce

1. `copier copy --trust --defaults --data project_name=foo --data author='Foo Bar' --data author_email='foo@b.ar' https://github.com/salt-extensions/salt-extension-copier foo`
2. `cd foo; git init && git add . && git commit -m "initial commit"`
3. `rm tests/functional/modules/test_foo.py && git commit -am rm`
4. `copier update --trust --skip-answered`
5. `git status` [shows new, untracked `tests/functional/modules/test_foo.py`]

### Expected behavior

The path to stay absent if it was deleted after project generation, as it's usually the case.

### Operating system

macOS

### Operating system distribution and version

14.6

### Copier version

copier 9.1.0

### Python version

CPython 3.11

### Installation method

pipx+pypi

### Additional context

The following code recreates the already deleted file:

https://github.com/copier-org/copier/blob/6fd3ad4af688dae998c0fa77e186e4b4666da7b3/copier/main.py#L954-L963

The diff contains the deleted file, it would be removed usually:

https://github.com/copier-org/copier/blob/6fd3ad4af688dae998c0fa77e186e4b4666da7b3/copier/main.py#L1006-L1010

But `git apply` is told to ignore changes to it, hence it remains:

https://github.com/copier-org/copier/blob/6fd3ad4af688dae998c0fa77e186e4b4666da7b3/copier/main.py#L1029-L1033

A solution could be to:
1. Create another diff between the old copy and the real dest (edit: dest copy, the code changed a bit between 9.1 and current HEAD) with `--diff-filter=D`
2. When applying the changes, first run `git apply --include <skip_if_exists-path-1> [...]` with the second diff on stdin (only if there are any `skip_if_exists` paths)
3. Then continue as usual.

**Comment by sisp** [comment] 2024-08-04 09:22
Thanks for raising this problem, @lkubb! :pray:

I left a comment in your PR with an alternative implementation idea. But I've also been thinking about the meaning and expected behavior of `skip_if_exists`. I think the original intention was to skip updating an existing file, e.g. because the generated content is non-determinstic. Perhaps also avoiding to overwrite an existing file during both `copy` and `update` is conceivable when generating a *sub*project (i.e., applying multiple templates to the same directory). If we never re-create a user-deleted file which is listed in `skip_if_exists`, then it'll be impossible to recover from this deletion using Copier, i.e. Copier will never re-create it. I wonder whether that's good behavior.

If you want to delete a file that is listed in `skip_if_exists`, how about passing the `--exclude` flag to the `copier {copy,update} ...` command instead to avoid generating it in the first place? This value is not recorded in the answers file though, perhaps something we should consider; otherwise, you need to remember to pass the same list of path patterns to `--exclude` on every update. If we recorded these path patterns, we might need a way to remove some of them again later, perhaps using a new `--include` flag.

WDYT?

**Comment by lkubb** [comment] 2024-08-04 09:41
> I left a comment in your PR with an alternative implementation idea.

@sisp Thank you! I'm currently looking into your proposal.

> But I've also been thinking about the meaning and expected behavior of `skip_if_exists`. I think the original intention was to skip updating an existing file, e.g. because the generated content is non-determinstic.

This would be one example. Another one, which the above-mentioned template intends to do, is to generate example code which should always be amended in the final project. `skip_if_exists` then prevents update conflicts when the template's examples are changed.

> If we never re-create a user-deleted file which is listed in `skip_if_exists`, then it'll be impossible to recover from this deletion using Copier, i.e. Copier will never re-create it. I wonder whether that's good behavior.

I'm only proposing to align the `update` behavior between paths that are listed in `skip_if_exists` with those that are not. Both can still be recovered using `copier recopy`.

> If you want to delete a file that is listed in `skip_if_exists`, how about passing the `--exclude` flag to the `copier {copy,update} ...` command instead to avoid generating it in the first place?

This would break the example file use case I described above.

> This value is not recorded in the answers file though, perhaps something we should consider; otherwise, you need to remember to pass the same list of path patterns to `--exclude` on every update. If we recorded these path patterns, we might need a way to remove some of them again later, perhaps using a new `--include` flag.

I like this proposal in general since it is project-specific configuration, just not as a workaround for this behavior. Copier not remembering those after project generation is something that came up while writing [Renovate support for Copier](https://github.com/renovatebot/renovate/pull/29215) (https://github.com/renovatebot/renovate/discussions/25538#discussioncomment-9532223, see details at the bottom).

**Comment by lkubb** [comment] 2024-08-07 15:05
> I'm not sure this is a bug. ˋskip_if_existsˋ shouldn't skip if it doesn't exist (obviously). If it did, that'd be a bug.

I agree for the `copy`/`recopy` commands. An `update` has different semantics since its intention is to apply custom changes on top of a newer (or the same) base. I would expect custom deletions to be honored as well. Mind that this is the case for files not listed in `skip_if_exists` (at least until the corresponding template changes).

Which problems does the current behavior of always recreating the file on update solve (if it's intentional)? And why should it be different for files that are not listed there?

> One use case is when the data you supply is just a foolish bootstrapping template that you expect the user will change a lot and those changes won't have any importance for the template itself.

In essence, this is why this behavior stumped me. I'm not saying the mentioned template is just a "foolish" bootstrapping template, but it has these bootstrapping parts. Different Salt module types have different predefined required methods (they are not changing). It helps to have an initial template that can be filled by users, but they can add more than one module of the same type or name it differently.

> What you really want is ˋexcludeˋ, which really excludes the thing. Or, probably, just don't add it to ˋskip_if_existsˋ, and IIUC copier won't recreate it unless changed in the template.

Not adding it to `skip_if_exists` would help until an example file changes for some reason, correct. Then it causes unnecessary merge conflicts.

When examples can have small changes from time to time, there are several issues with `exclude`:

* Copier does not remember `exclude` in `.copier-answers.yml`, so each `copier update` invocation needs it.
* I need to teach users of the template about having to exclude the files during updates if they want to get rid of them.
* I can't use the newly released RenovateBot support for Copier since it does not support passing `exclude`.

**Comment by yajo** [comment] 2024-08-11 06:34
So, the whole point of this is: what should copier do if one file listed to skip if exists happens to be deleted in the subproject but changed in the template?

Should it behave like if it were listed in exclude? (What you propose) Or should it behave as a merge conflict and write the file? (Current behavior) 

IMHO current behavior is correct because the option is called "skip if exists", not "skip if updating". The fact is it doesn't exist, so it shouldn't be skipped. This behavior is the same for any other file under the same circumstances. 

However then the next question is: how to give you the power to have a "skip if updating"? 😉

I think we could simply add a `_copier_conf.operation` variable that contains `copy`, `recopy` or `update`. Then you can use it to template `_exclude` and effectively "skip if updating". Does that look good to you? 😊

**Comment by yajo** [comment] 2024-08-12 08:33
Closing as duplicate of https://github.com/copier-org/copier/issues/1725.

**Closed by yajo** 2024-08-12 08:33 UTC
Labels: bug, triage

**Comment by lkubb** [comment] 2024-08-12 09:15
Thanks, your proposal would provide a way to do what I initially wanted.

Just some comments:

> Should it behave like if it were listed in exclude? (What you propose)

My proposal was to make the update behavior of deleted files consistent. Additionally, I think all project-deleted files should be excluded during `copy` (https://github.com/copier-org/copier/issues/1721) (or there should be a setting to enable this behavior), but I can see the case for a merge conflict as well.

The current `update` behavior is as follows:

|                        | not changed in template     | changed in template         |
|------------------------|-----------------------------|-----------------------------|
| **skip_if_exists**     | recreate, no merge conflict | recreate, no merge conflict |
| **not skip_if_exists** | stays absent                | recreate, no merge conflict |


> Or should it behave as a merge conflict and write the file? (Current behavior)

The current behavior does not report a merge conflict though.

> IMHO current behavior is correct because the option is called "skip if exists", not "skip if updating".

I agree with the linguistic logic, but imho it's surprising that a switch named "__skip__ if exists" increases the likelihood of a file to be recreated. This should be documented. I'm still not sure which problem this behavior solves though, the code seemed like it was unintentional.
