### ISSUE TITLE
"copy" action ignores templates specific answer file name if default is present.

### ISSUE THREAD

**Issue by hwine** [copier-org/copier#349] opened 2021-02-11 04:06 UTC
When a template has been installed which uses the default `.copier-answers.yml` file, subsequent attempts to install other templates, even if they specify a different answer file name, may fail.

## STR
N.B. all answers defaulted for both `copy` and `update` actions.
1. initialize empty git repo
1. `copier copy gh:pawamoy/copier-poetry .` # installs cleanly, uses default .copier-answers.yml file
1. commit all files
1. `copier update` # updates cleanly
1. `copier update` # even multiple times
1. `copier copy gh:copier-org/autopretty .`

Actual behavior:
- install fails with "Your are downgrading from 0.2.0 to v0.1.0. Downgrades are not supported." message.
- "0.2.0" comes from copier-poetry's value in the default answers file:
    ```bash
    $ shyaml get-value _commit <.copier-answers.yml ; echo
    0.2.0
    ```

Expected behavior:
- the "autopretty" template should be installed, using the `.copier-answers-autopretty.yml` file it specifies.

**Comment by Yajo** [comment] 2021-02-11 09:06
Hello, thanks for your detailed report and welcome to Copier!

I have been able to reproduce your issue, but AFAICS it's fixed in last alpha, so I'll close the bug because it'll be fixed in Copier 6.

However, I understand you might not want to use alpha software. In the mean time, probably it will help a lot if you specify manually the `-a` flag when using each template, or if you alter the default for `gh:pawamoy/copier-poetry` and save its answers in `.copier-answers.copier-poetry.yml` for example.

**Closed by Yajo** 2021-02-11 09:06 UTC
Labels: Type:Bug
