### ISSUE TITLE
Support json schema

### ISSUE THREAD

**Issue by Freed-Wu** [copier-org/copier#1489] opened 2024-01-23 12:55 UTC
### Actual Situation

Can `copier.yml` have a [json schema](https://json-schema.org/) and been published in [schemastore](https://www.schemastore.org/json/)?

### Desired Situation

Like [alacritty](https://github.com/alacritty/alacritty):

![Screenshot from 2024-01-11 17-31-20](https://github.com/ClementTsang/bottom/assets/32936898/2d4d2226-2259-4e6d-b164-7db6b2ef34cd)

### Proposed solution

This is a reference: <https://github.com/cmhughes/latexindent.pl/issues/206>

The steps are following:

1. Create a json schema
2. Add its URL to schemastore.

**Comment by yajo** [comment] 2024-01-24 18:29
Duplicate of #918.

**Closed by yajo** 2024-01-24 18:29 UTC
Labels: enhancement
