### ISSUE TITLE
Can't have two README files

### ISSUE THREAD

**Issue by amonteagudomoreno** [copier-org/copier#1318] opened 2023-09-07 10:14 UTC
### Describe the problem

I have a Bitbucket repository holding a template made with Copier, that repository has a README.md, the template also has a README.md.jinja, which will be copied to the project created from this template, here is my problem, I am excluding README.md to not copy the information of how to use the template project but this way the jinja with the steps to set up the project generated from the template is also not copied because having the same name. I have tried having README.rst in my project but since we are using Bitbucket Basic, it is not getting rendered by default in web.

Will be any possibility that excluding files from copying is first checked and then every other file ending in .jinja is rendered but copied, I do not see a case where a .jinja is not meant to be copied.

Regards

### Template

None

### Expected behavior

README.md is excluded but README.md.jinja is copied from the template

### Operating system

macOS

### Operating system distribution and version

Ventura 13.5.1

### Copier version

copier 8.1.0

### Python version

Python 3.9

### Installation method

pipx+pypi

**Comment by sisp** [comment] 2023-09-07 12:12
First, you don't need to exclude `README.md` because when you have both `README.md` and `README.md.jinja` then `README.md.jinja` will be copied/rendered to the destination. This snippet is responsible for the described behavior although it may not be so obvious why:

https://github.com/copier-org/copier/blob/b881f5131d9dc34b3423ba59feec95ce33b1a039/copier/main.py#L656-L657

Second, I'd always put the template files in a [subdirectory](https://copier.readthedocs.io/en/latest/configuring/#subdirectory) to separate them from other files in the repo that are not part of the template.

**Comment by yajo** [comment] 2023-09-07 14:09
Duplicate of #1238

**Closed as not planned by yajo** 2023-09-07 14:09 UTC
Labels: bug, triage
