### ISSUE TITLE
Copier Update doesn't read key/value from command-line if answers lack a question due to it being a secret.

### ISSUE THREAD

**Issue by jaccoh** [copier-org/copier#1215] opened 2023-06-26 12:39 UTC
### Describe the problem

So, I have this template, which among other things asks for a gitlab_token. Which ofcourse is a secret. It is therefore not stored as an answer in the answers file. Upon doing a copier update I get "ValueError: Question "gitlab_token" is required".

### Template

```yaml
snc_cluster_name:
    type: str
    help: What is the cluster name in ServiceNow? eg. k8c0000

cluster_type:
  type: str
  help: What is the cluster type?
  choices:
    This cluster will run Rancher, so "rancher": rancher
    This cluster is a downstream cluster, managed and deployed by an existing Rancher: downstream

directory_name:
  type: str
  help: This is the name of the git repository and thus it's directory name.
  default: "rke2_{{ cluster_type }}_cluster_{{ snc_cluster_name }}"

rancher_hostname:
  type: str
  help: We are installing Rancher. Rancher needs a round-robin FQDN (hostname) for it's agents to talk to Rancher. What is the hostname?
  when: "{{ cluster_type == 'rancher' }}"

rancher_lb_hostname:
  type: str
  help: We are installing Rancher. Rancher needs a LoadBalancer-pool FQDN (hostname) for it's web/api-interface for daily use. What is the LB hostname?
  when: "{{ cluster_type == 'rancher' }}"

certificate_cn:
  type: str
  help: We are installing Rancher. Rancher needs a TLS certificate matching both the Round-Robin and LB hostnames. What is the CN in Lemur so we can fetch it?
  when: "{{ cluster_type == 'rancher' }}"

master_rancher_hostname:
  type: str
  help: This will be a downstream cluster. For Rancher to be able to deploy it, we need to know which Rancher will do so. What is the hostname (FQDN) of this Rancher instance?
  when: "{{ cluster_type == 'downstream' }}"

token_user:
  type: str
  help: This will be a downstream cluster. For Rancher to be able to deploy it, we need an API-token (bearer token). What is the Access Key (username) of this token?
  when: "{{ cluster_type == 'downstream' }}"

token_pass:
  type: str
  help: This will be a downstream cluster. For Rancher to be able to deploy it, we need an API-token (bearer token). What is the Secret Key (password) of this token?
  when: "{{ cluster_type == 'downstream' }}"

k8s_fqdn:
  type: str
  help: This will be a downstream cluster. It needs a FQDN for the ACE. This should be load-balanced and have SSL-offloading. What is the FQDN?
  when: "{{ cluster_type == 'downstream' }}"

nameservers:
  type: str
  help: What are the upstream nameservers? eg. 10.0.1.1,10.0.1.2

needs_proxy:
  type: bool
  help: Does this cluster require a proxy for outgoing http(s) connections?
  default: True

proxy_host:
  type: str
  help: What is the hostname of the proxy?
  default: proxy.whatever.net

proxy_port:
  type: int
  help: What is the port number of the proxy?
  default: 8080

gitlab_token:
  type: str
  help: Please specify your gitlab token
  secret: True
  required: True

_exclude:
  - .idea
  - .git

_tasks:
  - hooks/fetch_snc.sh
  - hooks/git-work.py
  - hooks/fix_project_name.sh
```

### To Reproduce

1. Run "copier" copy to create a project.
2. Run copier update.

### Logs

```console
❯ copier update --UNSAFE
No git tags found in template; using HEAD as ref
Updating to template version 0.0.0.post20.dev0+166c24c
Traceback (most recent call last):
  File "/opt/homebrew/bin/copier", line 8, in <module>
    sys.exit(copier_app_run())
             ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/copier/8.0.0/libexec/lib/python3.11/site-packages/plumbum/cli/application.py", line 638, in run
    inst, retcode = subapp.run(argv, exit=False)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/copier/8.0.0/libexec/lib/python3.11/site-packages/plumbum/cli/application.py", line 633, in run
    retcode = inst.main(*tailargs)
              ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/copier/8.0.0/libexec/lib/python3.11/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/copier/8.0.0/libexec/lib/python3.11/site-packages/copier/cli.py", line 66, in handle_exceptions
    return method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/copier/8.0.0/libexec/lib/python3.11/site-packages/copier/cli.py", line 369, in main
    ).run_update()
      ^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/copier/8.0.0/libexec/lib/python3.11/site-packages/copier/main.py", line 809, in run_update
    self._apply_update()
  File "/opt/homebrew/Cellar/copier/8.0.0/libexec/lib/python3.11/site-packages/copier/main.py", line 835, in _apply_update
    old_worker.run_copy()
  File "/opt/homebrew/Cellar/copier/8.0.0/libexec/lib/python3.11/site-packages/copier/main.py", line 732, in run_copy
    src_abspath = self.template_copy_root
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/functools.py", line 1001, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/copier/8.0.0/libexec/lib/python3.11/site-packages/copier/main.py", line 716, in template_copy_root
    subdir = self._render_string(self.template.subdirectory) or ""
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/copier/8.0.0/libexec/lib/python3.11/site-packages/copier/main.py", line 690, in _render_string
    return tpl.render(**self._render_context())
                        ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/copier/8.0.0/libexec/lib/python3.11/site-packages/copier/main.py", line 297, in _render_context
    "answers_file": self.answers_relpath,
                    ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/functools.py", line 1001, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/copier/8.0.0/libexec/lib/python3.11/site-packages/copier/main.py", line 476, in answers_relpath
    return Path(template.render(**self.answers.combined))
                                  ^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/functools.py", line 1001, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/copier/8.0.0/libexec/lib/python3.11/site-packages/copier/main.py", line 453, in answers
    raise ValueError(f'Question "{var_name}" is required')
ValueError: Question "gitlab_token" is required
```

### Expected behavior

It should either ask for the variable input or accept it from command-line via -d.

### Operating system

macOS

### Operating system distribution and version

13.4.1

### Copier version

copier 8.0.0

### Python version

Python 3.11.3

### Installation method

distro package

**Comment by sisp** [comment] 2023-06-26 13:31
This problem has been raised in #1177 already. Our [suggested solution is to use a default value](https://github.com/copier-org/copier/issues/1177#issuecomment-1585556997) (e.g. empty string for string-type questions) fir secret questions. We're planning to extend Copier to raise an error when a secret question has no default value for better user feedback.

I'll close this issue as a duplicate of #1177. Please feel free to join the discussion there if you see need.

**Closed** 2023-06-26 13:32 UTC
Labels: bug, triage
