### ISSUE TITLE
[Windows] `copier update .` can't find the parent template despite _src_path being defined

### ISSUE THREAD

**Issue by Twisted-Code** [copier-org/copier#1742] opened 2024-08-21 21:41 UTC
### Describe the problem

As a first-time user, I installed copier using pipx then ran `pipx run copier copy gh:FallingColors/hexdummy .`, per the instructions in [that project](https://github.com/FallingColors/hexdummy)'s readme. Answered all the template questions, great, so far so good. But then I ran into problems when I tried to use `copier update .` to change some of my answers. It throws `TypeError: template not found`, and I'm not quite sure why since I think I followed the documentation, both on readthedocs and in the command usage output. I also double checked that `_src_path` exists in the answers file, and it seems it does:
![image](https://github.com/user-attachments/assets/c090b712-e34c-4a7c-9c6b-10049f987ab1)
The only other hypotheses I have at the moment are:
1. that I haven't finished initializing GIT in the destination folder (but I did at least create a repo, just haven't made the initial commit) or
2. that it's some weird Windows quirk, like maybe Windows is somehow causing it to look in the wrong place for the answers file (even though this is the same shell session that created that file, and I'm running).
For now I'm going to work around it by just biting the bullet and re-answering everything, but it would be really nice to be able to avoid that if I have to update the template again in the future.

### Template

gh:FallingColors/hexdummy. It's a template for creating add-ons for a Minecraft mod called Hex Casting

### To Reproduce

1. Open a (GIT for Windows) git-bash terminal. For me this pulls up a MingW window with the targeted path as its working directory.
2. install copier (I used pipx, hence the `pipx run` in subsequent commands)
3. Run `pipx run copier copy gh:FallingColors/hexdummy .`
4. answer all questions sensibly
5. run `pipx run copier update .` (or omit the `.`, it didn't seem to matter either way)
6. TypeError is thrown

### Logs

```console
(most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\usernamehere\pipx\.cache\5c243c171212858\Scripts\copier.exe\__main__.py", line 7, in <module>
  File "C:\Users\usernamehere\pipx\.cache\5c243c171212858\lib\site-packages\plumbum\cli\application.py", line 638, in run
    inst, retcode = subapp.run(argv, exit=False)
  File "C:\Users\usernamehere\pipx\.cache\5c243c171212858\lib\site-packages\plumbum\cli\application.py", line 633, in run
    retcode = inst.main(*tailargs)
  File "C:\Users\usernamehere\pipx\.cache\5c243c171212858\lib\site-packages\copier\cli.py", line 425, in main
    return _handle_exceptions(inner)
  File "C:\Users\usernamehere\pipx\.cache\5c243c171212858\lib\site-packages\copier\cli.py", line 70, in _handle_exceptions
    method()
  File "C:\Users\usernamehere\pipx\.cache\5c243c171212858\lib\site-packages\copier\cli.py", line 415, in inner
    with self._worker(
  File "C:\Users\usernamehere\pipx\.cache\5c243c171212858\lib\site-packages\copier\main.py", line 228, in __exit__
    raise value
  File "C:\Users\usernamehere\pipx\.cache\5c243c171212858\lib\site-packages\copier\cli.py", line 423, in inner
    worker.run_update()
  File "C:\Users\usernamehere\pipx\.cache\5c243c171212858\lib\site-packages\copier\main.py", line 857, in run_update
    self._check_unsafe("update")
  File "C:\Users\usernamehere\pipx\.cache\5c243c171212858\lib\site-packages\copier\main.py", line 242, in _check_unsafe
    if self.template.jinja_extensions:
  File "C:\Program Files\Python310\lib\functools.py", line 981, in __get__
    val = self.func(instance)
  File "C:\Users\usernamehere\pipx\.cache\5c243c171212858\lib\site-packages\copier\main.py", line 787, in template
    raise TypeError("Template not found")
TypeError: Template not found

```
Here's an example copying session that produces the error:
```

redactedusername@redactedhostname MINGW64 /n/PDD/projects/Crystalline Containment/workspace 3 (1.19-dev)
$ pipx run copier copy gh:FallingColors/hexdummy .
≡ƒÄñ modid
   crycon
≡ƒÄñ author
   Twisted_Code
≡ƒÄñ classname base (eg. 'Crycon' -> 'CryconClient.java')
   Crycon
≡ƒÄñ display_name
   Crystalline Containment
≡ƒÄñ description
   A Hex Casting addon about taking living (or in some cases undead) things and shoving them into very tight spaces. Forcibly.
≡ƒÄñ license
   GNU GPL 3.0
≡ƒÄñ github_repo
   crystalline-containment
≡ƒÄñ default_branch
   main
≡ƒÄñ sources_url
   https://github.com/Twisted-Code/crystalline-containment
≡ƒÄñ homepage_url
   https://twisted-code.github.io/crystalline-containment
≡ƒÄñ initial_mod_version
   0.0.1
≡ƒÄñ java_version (int)
   17
≡ƒÄñ hexcasting_version
   0.10.3
≡ƒÄñ package
   com.entertainment.witchbrew.twisted.crycon
≡ƒÄñ Capitalize platform directory names? (eg. Common vs common)
   No
≡≡ƒÄñ Mappings (note: Hex Casting uses Mojmap)
   Yarn

Copying from template version 0.0.9
 identical  .
    create  .gitignore
    create  .hexdoc-template-inputs.yml
    create  build.gradle
    create  CHANGELOG.md
    create  gradle
    create  gradle\wrapper
    create  gradle\wrapper\gradle-wrapper.jar
    create  gradle\wrapper\gradle-wrapper.properties
    create  gradle.properties
    create  gradlew
    create  gradlew.bat
    create  README.md
    create  settings.gradle
    create  common
    create  common\build.gradle
    create  common\src
    create  common\src\main
    create  common\src\main\java
    create  common\src\main\java\com\entertainment\witchbrew\twisted\crycon
    create  common\src\main\java\com\entertainment\witchbrew\twisted\crycon\api
    create  common\src\main\java\com\entertainment\witchbrew\twisted\crycon\api\config
    create  common\src\main\java\com\entertainment\witchbrew\twisted\crycon\api\config\CryconConfig.java
    create  common\src\main\java\com\entertainment\witchbrew\twisted\crycon\casting
    create  common\src\main\java\com\entertainment\witchbrew\twisted\crycon\casting\patterns
    create  common\src\main\java\com\entertainment\witchbrew\twisted\crycon\casting\patterns\math
    create  common\src\main\java\com\entertainment\witchbrew\twisted\crycon\casting\patterns\math\OpSignum.kt
    create  common\src\main\java\com\entertainment\witchbrew\twisted\crycon\casting\patterns\spells
    create  common\src\main\java\com\entertainment\witchbrew\twisted\crycon\casting\patterns\spells\OpCongrats.kt
    create  common\src\main\java\com\entertainment\witchbrew\twisted\crycon\client
    create  common\src\main\java\com\entertainment\witchbrew\twisted\crycon\client\LookClient.java
    create  common\src\main\java\com\entertainment\witchbrew\twisted\crycon\mixin
    create  common\src\main\java\com\entertainment\witchbrew\twisted\crycon\mixin\CryconMixin.java
    create  common\src\main\java\com\entertainment\witchbrew\twisted\crycon\networking
    create  common\src\main\java\com\entertainment\witchbrew\twisted\crycon\networking\SetLookPitchS2CMsg.java
    create  common\src\main\java\com\entertainment\witchbrew\twisted\crycon\networking\CryconNetworking.java
    create  common\src\main\java\com\entertainment\witchbrew\twisted\crycon\registry
    create  common\src\main\java\com\entertainment\witchbrew\twisted\crycon\registry\CryconIotaTypeRegistry.java
    create  common\src\main\java\com\entertainment\witchbrew\twisted\crycon\registry\CryconItemRegistry.java
    create  common\src\main\java\com\entertainment\witchbrew\twisted\crycon\registry\CryconPatternRegistry.java
    create  common\src\main\java\com\entertainment\witchbrew\twisted\crycon\Crycon.java
    create  common\src\main\java\com\entertainment\witchbrew\twisted\crycon\CryconAbstractions.java
    create  common\src\main\java\com\entertainment\witchbrew\twisted\crycon\CryconClient.java
    create  common\src\main\resources
    create  common\src\main\resources\architectury.common.json
    create  common\src\main\resources\assets
    create  common\src\main\resources\assets\crycon
    create  common\src\main\resources\assets\crycon\lang
    create  common\src\main\resources\assets\crycon\lang\en_us.json
    create  common\src\main\resources\data
    create  common\src\main\resources\data\crycon
    create  common\src\main\resources\data\crycon\patchouli_books
    create  common\src\main\resources\data\crycon\patchouli_books\cryconbook
    create  common\src\main\resources\data\crycon\patchouli_books\cryconbook\book.json
    create  common\src\main\resources\data\crycon\patchouli_books\cryconbook\en_us
    create  common\src\main\resources\data\crycon\patchouli_books\cryconbook\en_us\entries
    create  common\src\main\resources\data\crycon\patchouli_books\cryconbook\en_us\entries\patterns
    create  common\src\main\resources\data\crycon\patchouli_books\cryconbook\en_us\entries\patterns\dummy_actions.json
    create  common\src\main\resources\data\crycon\patchouli_books\cryconbook\en_us\entries\patterns\spells
    create  common\src\main\resources\data\crycon\patchouli_books\cryconbook\en_us\entries\patterns\spells\dummy_spells.json
    create  common\src\main\resources\icon.png
    create  common\src\main\resources\crycon-common.mixins.json
    create  common\src\main\resources\crycon.accesswidener
    create  fabric
    create  fabric\build.gradle
    create  fabric\src
    create  fabric\src\main
    create  fabric\src\main\java
    create  fabric\src\main\java\com\entertainment\witchbrew\twisted\crycon
    create  fabric\src\main\java\com\entertainment\witchbrew\twisted\crycon\fabric
    create  fabric\src\main\java\com\entertainment\witchbrew\twisted\crycon\fabric\CryconAbstractionsImpl.java
    create  fabric\src\main\java\com\entertainment\witchbrew\twisted\crycon\fabric\CryconClientFabric.java
    create  fabric\src\main\java\com\entertainment\witchbrew\twisted\crycon\fabric\CryconConfigFabric.java
    create  fabric\src\main\java\com\entertainment\witchbrew\twisted\crycon\fabric\CryconFabric.java
    create  fabric\src\main\resources
    create  fabric\src\main\resources\fabric.mod.json
    create  fabric\src\main\resources\crycon.mixins.json
    create  forge
    create  forge\build.gradle
    create  forge\gradle.properties
    create  forge\src
    create  forge\src\main
    create  forge\src\main\java
    create  forge\src\main\java\com\entertainment\witchbrew\twisted\crycon
    create  forge\src\main\java\com\entertainment\witchbrew\twisted\crycon\forge
    create  forge\src\main\java\com\entertainment\witchbrew\twisted\crycon\forge\CryconAbstractionsImpl.java
    create  forge\src\main\java\com\entertainment\witchbrew\twisted\crycon\forge\CryconClientForge.java
    create  forge\src\main\java\com\entertainment\witchbrew\twisted\crycon\forge\CryconConfigForge.java
    create  forge\src\main\java\com\entertainment\witchbrew\twisted\crycon\forge\CryconForge.java
    create  forge\src\main\resources
    create  forge\src\main\resources\META-INF
    create  forge\src\main\resources\META-INF\mods.toml
    create  forge\src\main\resources\pack.mcmeta
    create  forge\src\main\resources\crycon.mixins.json
    create  .copier-answers.hexdummy.yml



redactedusername@redactedhostname MINGW64 /n/PDD/projects/Crystalline Containment/workspace 3 (1.19-dev)
$ pipx run copier update
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\redactedusername\pipx\.cache\5c243c171212858\Scripts\copier.exe\__main__.py", line 7, in <module>
  File "C:\Users\redactedusername\pipx\.cache\5c243c171212858\lib\site-packages\plumbum\cli\application.py", line 638, in run
    inst, retcode = subapp.run(argv, exit=False)
  File "C:\Users\redactedusername\pipx\.cache\5c243c171212858\lib\site-packages\plumbum\cli\application.py", line 633, in run
    retcode = inst.main(*tailargs)
  File "C:\Users\redactedusername\pipx\.cache\5c243c171212858\lib\site-packages\copier\cli.py", line 425, in main
    return _handle_exceptions(inner)
  File "C:\Users\redactedusername\pipx\.cache\5c243c171212858\lib\site-packages\copier\cli.py", line 70, in _handle_exceptions
    method()
  File "C:\Users\redactedusername\pipx\.cache\5c243c171212858\lib\site-packages\copier\cli.py", line 415, in inner
    with self._worker(
  File "C:\Users\redactedusername\pipx\.cache\5c243c171212858\lib\site-packages\copier\main.py", line 228, in __exit__
    raise value
  File "C:\Users\redactedusername\pipx\.cache\5c243c171212858\lib\site-packages\copier\cli.py", line 423, in inner
    worker.run_update()
  File "C:\Users\redactedusername\pipx\.cache\5c243c171212858\lib\site-packages\copier\main.py", line 857, in run_update
    self._check_unsafe("update")
  File "C:\Users\redactedusername\pipx\.cache\5c243c171212858\lib\site-packages\copier\main.py", line 242, in _check_unsafe
    if self.template.jinja_extensions:
  File "C:\Program Files\Python310\lib\functools.py", line 981, in __get__
    val = self.func(instance)
  File "C:\Users\redactedusername\pipx\.cache\5c243c171212858\lib\site-packages\copier\main.py", line 787, in template
    raise TypeError("Template not found")
TypeError: Template not found

redactedusername@redactedhostname MINGW64 /n/PDD/projects/Crystalline Containment/workspace 3 (1.19-dev)
$ pipx run copier update --help
copier update 9.3.1

Update a subproject from its original template

The copy must have a valid answers file which contains info from the last Copier execution, including the source template (it must be a key
called `_src_path`).

If that file contains also `_commit`, and `destination_path` is a git repository, this command will do its best to respect the diff that youhave generated since the last `copier` execution. To avoid that, use `copier recopy` instead.

Usage:
    copier update [SWITCHES] [destination_path=.]

Meta-switches:
    -h, --help                              Prints this help message and quits
    --help-all                              Prints help messages of all sub-commands and quits
    -v, --version                           Prints the program's version and quits

Switches:
    -A, --skip-answered                     Skip questions that have already been answered
    -T, --skip-tasks                        Skip template tasks execution
    --UNSAFE, --trust                       Allow templates with unsafe features (Jinja extensions, migrations, tasks)
    -a, --answers-file VALUE:str            Update using this path (relative to `destination_path`) to find the answers file
    -c, --context-lines VALUE:int           Lines of context to use for detecting conflicts. Increase for accuracy, decrease for
                                            resilience.; the default is 3
    -d, --data VARIABLE=VALUE:str           Make VARIABLE available as VALUE when rendering the template; may be given multiple times
    --data-file PATH:ExistingFile           Load data from a YAML file
    -g, --prereleases                       Use prereleases to compare template VCS tags.
    -l, -f, --defaults                      Use default answers to questions, which might be null if not specified.
    -n, --pretend                           Run but do not make any changes
    -o, --conflict VALUE:{rej, inline}      Behavior on conflict: Create .rej files, or add inline conflict markers.; the default is inline
    -q, --quiet                             Suppress status output
    -r, --vcs-ref VALUE:str                 Git reference to checkout in `template_src`. If you do not specify it, it will try to checkout
                                            the latest git tag, as sorted using the PEP 440 algorithm. If you want to checkout always the
                                            latest version, use `--vcs-ref=HEAD`.
    -s, --skip VALUE:str                    Skip specified files if they exist already; may be given multiple times
    -x, --exclude VALUE:str                 A name or shell-style pattern matching files or folders that must not be copied; may be given
                                            multiple times


redactedusername@redactedhostname MINGW64 /n/PDD/projects/Crystalline Containment/workspace 3 (1.19-dev)
$ pipx run copier update --version
copier update 9.3.1
```

### Expected behavior

I expected it to be able to find the template from the answers config, like the usage output seems to imply it would.

### Operating system

Windows

### Operating system distribution and version

Windows 10 (build 19045.4651)

### Copier version

9.3.1

### Python version

CPython 3.10.2

### Installation method

pipx+pypi

### Additional context

It occurs to me just as I finish typing up this issue that I might need to update Python. Istg, if that's my issue I'm not only going to close this issue I'm going to add "I'm a fucking moron" to the title before I do. Nonetheless... I've come this far so I may as well post.

**Comment by Twisted-Code** [comment] 2024-08-21 21:50
Oh thank God, it wasn't my Python version? Reproduced with Python 3.11.9
![image](https://github.com/user-attachments/assets/21b765c7-00d1-4515-8386-73a91a35a82f)

**Comment by sisp** [comment] 2024-08-23 10:13
Thanks for reporting this problem, @Twisted-Code! :pray: I can reproduce the problem also on Linux. I'll look into it.

**Comment by sisp** [comment] 2024-08-23 10:19
Got it. The answer is simple: Run `copier update --answers-file .copier-answers.hexdummy.yml` (after Git-initializing the project). Passing the answers file explicitly is necessary because the [template uses a custom answers file name](https://github.com/FallingColors/hexdummy/blob/4b559c97acec2f466d02f7d20b5a5be08513404c/copier.yml#L4) which Copier cannot guess. Same as #1740.

I'm closing this issue because there's no bug, but feel free to keep commenting.

**Closed by sisp** 2024-08-23 10:19 UTC
Labels: bug, triage

**Comment by Twisted-Code** [comment] 2024-08-24 22:24
Oh, I see! I didn't even notice the file wasn't using the default name. Maybe I should have asked the template owner why the update command wasn't working, I imagine they would have (hopefully) remembered that detail.

For the record, I still consider this a bug. I think it should catch and handle the exception, perhaps by logging it and printing an error message?
