### ISSUE TITLE
bug: When using a local .git repo as src, it uses the last commit instead of the actual files

### ISSUE THREAD

**Issue by nstrelow** [copier-org/copier#392] opened 2021-04-19 16:48 UTC
This is some mad magic 🧙 🔮 💥 

For some reason, when I specify a local directory containing a git repo, copier ignores all  local changes and just uses the state of the last git commit.

This is super confusing, especially when building a new template step by step.

**Comment by Yajo** [comment] 2021-04-21 14:26
Duplicate of #184.

**Closed by Yajo** 2021-04-21 14:26 UTC
Labels: bug
