### ISSUE TITLE
several templates in one repo

### ISSUE THREAD

**Issue by m-birke** [copier-org/copier#1279] opened 2023-08-01 12:43 UTC
### Actual Situation

I have a git repo with several templates collected, each one has its own directory

### Desired Situation

It would be cool if it would be possible to specify a directory within a git repo where the template is located.

### Proposed solution

additional param for copier copy like --directory ?

[Like cookiecutter is doin it](https://cookiecutter.readthedocs.io/en/stable/cli_options.html#cmdoption-cookiecutter-directory)

**Comment by sisp** [comment] 2023-08-02 07:45
This is answered in the docs: https://copier.readthedocs.io/en/latest/configuring/#subdirectory

> **Can I have multiple templates in a single repo using this option?**
>
> The Copier recommendation is: **1 template = 1 Git repository.**
>
> [...]

Duplicate of #315 #1078.

**Closed by sisp** 2023-08-02 07:45 UTC
Labels: enhancement
