### ISSUE TITLE
bug: Do not remove destination folder when destination folder is './'.

### ISSUE THREAD

**Issue by normoes** [copier-org/copier#406] opened 2021-05-14 19:19 UTC
**Describe the problem**
I had a typo in the answers file template. I called it:
```
[[_copier_conf.answers-file]].jinja
# instead of
[[_copier_conf.answers_file]].jinja
```

Then I ran:
```
#  I even added 'prevent', without it is the same.
copier  --pretend copy  'git@github.com:some/repo.git'  ./
```

I received an error:
```
Something went wrong. Removing destination folder.
Traceback (most recent call last):
  File "/home/norman/.local/bin/copier", line 8, in <module>
    sys.exit(CopierApp.run())
  File "/home/norman/.local/lib/python3.8/site-packages/plumbum/cli/application.py", line 614, in run
    inst, retcode = subapp.run(argv, exit=False)
  File "/home/norman/.local/lib/python3.8/site-packages/plumbum/cli/application.py", line 609, in run
    retcode = inst.main(*tailargs)
  File "/home/norman/.local/lib/python3.8/site-packages/copier/cli.py", line 38, in _wrapper
    return method(*args, **kwargs)
  File "/home/norman/.local/lib/python3.8/site-packages/copier/cli.py", line 252, in main
    self.parent._copy(template_src, destination_path)
  File "/home/norman/.local/lib/python3.8/site-packages/copier/cli.py", line 173, in _copy
    return copy(
  File "/home/norman/.local/lib/python3.8/site-packages/copier/main.py", line 147, in copy
    copy_local(conf=conf)
  File "/home/norman/.local/lib/python3.8/site-packages/copier/main.py", line 198, in copy_local
    source_paths = get_source_paths(
  File "/home/norman/.local/lib/python3.8/site-packages/copier/main.py", line 334, in get_source_paths
    dst_name = render.string(dst_name)
  File "/home/norman/.local/lib/python3.8/site-packages/copier/tools.py", line 167, in string
    return tmpl.render(**self.data)
  File "/home/norman/.local/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/norman/.local/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/norman/.local/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 1, in top-level template code
jinja2.exceptions.UndefinedError: 'copier.config.objects.ConfigData object' has no attribute 'answers'
```

As you can see, the error mentions it as well, the `destination folder` was removed. In my case this folder is `./` and my project/'s repository was deleted.
```
Something went wrong. Removing destination folder.
```
If I am in `/some/path/project.git` this very path will be deleted including `project.git`.

**Template**
`copier.yml`:
```
_templates_suffix: .jinja
_skip_if_exists:
  - CHANGELOG.md
  - README.md
project_name:
  default: <project_name>
```

`[[_copier_conf.answers-file]]jinja`:
```
# Changes here will be overwritten by copier.
[[_copier_answers|to_nice_yaml]]
```

**To Reproduce**

**Expected behavior**
When using `./` the `destination folder`is not deleted.

**Screenshots/screencasts**

**Environment**
 - OS: Ubuntu 20.04.2 LTS
 - Copier version: copier 5.1.0
 - Python version: Python 3.8.5
 - Installation method: pip

**Additional context**

**Comment by Yajo** [comment] 2021-05-15 04:25
Thanks for your report. I believe this is a duplicate of #285. Can you still reproduce if you install from master? If yes, please reopen.

**Closed by Yajo** 2021-05-15 04:25 UTC
Labels: bug
