### ISSUE TITLE
Allow migrations that run on every update

### ISSUE THREAD

**Issue by FlorianLudwig** [copier-org/copier#872] opened 2022-11-18 10:38 UTC
**Is your feature request related to a problem? Please describe.**
A migration that is executed on every migration

**Describe the solution you'd like**

```
_migrations:
    - version: "*"
```

**Comment by pawamoy** [comment] 2022-11-18 10:41
Couldn't you use a task then?

**Comment by FlorianLudwig** [comment] 2022-11-18 11:03
@pawamoy no, tasks are executed after the merge, I want to execute tasks before that. For example deleting the `poetry.lock`

**Comment by yajo** [comment] 2022-11-19 07:38
Duplicate of #240

**Closed by yajo** 2022-11-19 07:38 UTC
Labels: enhancement
