### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by LeoDeJaneiro** [copier-org/copier#583] opened 2022-02-26 13:44 UTC
**Describe the problem**
Cannot run the Copier CLI after pip install.

**To Reproduce**

1. Install copier through ```pip install copier``` or ```pipx install copier```, then ```asdf reshim``` to make the module available in the path (asdf managed python)
3. Run ```copier --help```
5. See error

<details>

```
Traceback (most recent call last):
  File "/Users/l/.asdf/installs/python/3.8.12/bin/copier", line 5, in <module>
    from copier.cli import CopierApp
  File "/Users/l/.asdf/installs/python/3.8.12/lib/python3.8/site-packages/copier/__init__.py", line 3, in <module>
    from .main import *  # noqa
  File "/Users/l/.asdf/installs/python/3.8.12/lib/python3.8/site-packages/copier/main.py", line 18, in <module>
    from .config import make_config
  File "/Users/l/.asdf/installs/python/3.8.12/lib/python3.8/site-packages/copier/config/__init__.py", line 1, in <module>
    from .factory import make_config  # noqa
  File "/Users/l/.asdf/installs/python/3.8.12/lib/python3.8/site-packages/copier/config/factory.py", line 13, in <module>
    from .user_data import load_answersfile_data, load_config_data, query_user_data
  File "/Users/l/.asdf/installs/python/3.8.12/lib/python3.8/site-packages/copier/config/user_data.py", line 11, in <module>
    from jinja2 import UndefinedError
  File "/Users/l/.asdf/installs/python/3.8.12/lib/python3.8/site-packages/jinja2/__init__.py", line 12, in <module>
    from .environment import Environment
  File "/Users/l/.asdf/installs/python/3.8.12/lib/python3.8/site-packages/jinja2/environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "/Users/l/.asdf/installs/python/3.8.12/lib/python3.8/site-packages/jinja2/defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "/Users/l/.asdf/installs/python/3.8.12/lib/python3.8/site-packages/jinja2/filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/Users/l/.asdf/installs/python/3.8.12/lib/python3.8/site-packages/markupsafe/__init__.py)
```

</details>

**Expected behavior**
Copier CLI should not error out. Any hints on this are appreciated.

**Environment**
 - OS: MacOs 12x, M1 ARM chip
 - Copier version: 5.1.0
 - Python versions: 3.8.12 / 3.9.9
 - Installation method: pip / pipx

**Comment by Yajo** [comment] 2022-02-26 14:32
Duplicate of #574.

**Closed by Yajo** 2022-02-26 14:32 UTC
Labels: bug
