### ISSUE TITLE
latest v9 release missing from pypi

### ISSUE THREAD

**Issue by branchvincent** [copier-org/copier#1391] opened 2023-10-29 20:14 UTC
### Describe the problem

Thanks for copier 😄! Just noticed the v9.0.0 release [failed](https://github.com/copier-org/copier/actions/runs/6604116128/job/17938108959) and didn't get published to PyPI

### Template

N/A

### Expected behavior

N/A

### Operating system

macOS

### Operating system distribution and version

N/A

### Copier version

N/A

### Python version

N/A

### Installation method

pipx+pypi

**Comment by sisp** [comment] 2023-10-29 20:24
Duplicate of https://github.com/copier-org/copier/discussions/1377#discussioncomment-7410774.

**Closed** 2023-10-29 20:26 UTC
Labels: bug, triage
