### ISSUE TITLE
bug: Using a local path e.g. `copier that-template a-new-folder` still uses git if `that-template` is a repo 

### ISSUE THREAD

**Issue by dennisroche** [copier-org/copier#412] opened 2021-06-15 02:20 UTC
**Describe the problem**

Perhaps this isn't a bug and the workflow needs documentation. Underlying issue is "how do you test templates locally _without_ committing the changes"? 

**To Reproduce**

1. Building or extending a template and want to test locally
1. Inside the `that-template` folder 
1. Run `copier . ./tmp`

**Expected behavior**

I would expect `copier` to use the local changes instead of the git repo. Perhaps better illustrated in the screen below where I modified `autoprettier` to have an invalid config (using `string` not `str` - a real world example 🤦‍♂️).

I would expect `copier` to use the `HEAD` only when I specify the full git url e.g. `copier copy https://github.com/copier-org/autopretty.git .` (or one of the `gh` url shortcuts)

**Screenshots/screencasts**

![Screenshot 2021-06-15 101148](https://user-images.githubusercontent.com/4949392/121982496-2c914700-cdc2-11eb-8c49-dd6a2f31670f.png)

**Environment**
 - OS: `Windows`
 - Copier version: `copier 5.1.0`
 - Python version: `3.8.5`
 - Installation method: `pipx+pypi`
 
**Additional context**

Perhaps this isn't a bug and the workflow needs documentation

**Comment by Yajo** [comment] 2021-06-15 07:07
Hello, thanks for contributing this issue. Closing as duplicate of https://github.com/copier-org/copier/issues/184, feel free to continue the conversation there.

**Closed by Yajo** 2021-06-15 07:07 UTC
Labels: bug
