### ISSUE TITLE
Jinja import does not work inside conditional files

### ISSUE THREAD

**Issue by kielosz** [copier-org/copier#1164] opened 2023-05-25 16:16 UTC
### Describe the problem

I use jinja import like this:

```
{% from 'common.jinja' import var1 %}
{{var1}}
```

it works inside a static file with a name like ```file.jinja```. However when I try to use the above import in a conditional file named ```{% if shouldCreate %}file{% endif %}.jinja``` it gives an error as in the logs section.

### Template

copier.yaml:

```
shouldCreate:
  type: bool
_subdirectory: template
```

common.jinja:
```
{% set var1 = "test" %}
```

template/{% if shouldCreate %}file{% endif %}.jinja

```
{% from 'common.jinja' import var1 %}
{{var1}}
```

### Logs

```console
File "/Users/jsmith/.local/pipx/.cache/93c3d6722ebba87/bin/copier", line 8, in <module>
    sys.exit(copier_app_run())
             ^^^^^^^^^^^^^^^^
  File "/Users/jsmith/.local/pipx/.cache/93c3d6722ebba87/lib/python3.11/site-packages/plumbum/cli/application.py", line 639, in run
    inst, retcode = subapp.run(argv, exit=False)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jsmith/.local/pipx/.cache/93c3d6722ebba87/lib/python3.11/site-packages/plumbum/cli/application.py", line 634, in run
    retcode = inst.main(*tailargs)
              ^^^^^^^^^^^^^^^^^^^^
  File "/Users/jsmith/.local/pipx/.cache/93c3d6722ebba87/lib/python3.11/site-packages/copier/cli.py", line 68, in _wrapper
    return method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jsmith/.local/pipx/.cache/93c3d6722ebba87/lib/python3.11/site-packages/copier/cli.py", line 295, in main
    ).run_copy()
      ^^^^^^^^^^
  File "/Users/jsmith/.local/pipx/.cache/93c3d6722ebba87/lib/python3.11/site-packages/copier/main.py", line 715, in run_copy
    self._render_folder(src_abspath)
  File "/Users/jsmith/.local/pipx/.cache/93c3d6722ebba87/lib/python3.11/site-packages/copier/main.py", line 607, in _render_folder
    self._render_file(file)
  File "/Users/jsmith/.local/pipx/.cache/93c3d6722ebba87/lib/python3.11/site-packages/copier/main.py", line 524, in _render_file
    tpl = self.jinja_env.get_template(src_relpath)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jsmith/.local/pipx/.cache/93c3d6722ebba87/lib/python3.11/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jsmith/.local/pipx/.cache/93c3d6722ebba87/lib/python3.11/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jsmith/.local/pipx/.cache/93c3d6722ebba87/lib/python3.11/site-packages/jinja2/loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jsmith/.local/pipx/.cache/93c3d6722ebba87/lib/python3.11/site-packages/jinja2/environment.py", line 766, in compile
    return self._compile(source, filename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jsmith/.local/pipx/.cache/93c3d6722ebba87/lib/python3.11/site-packages/jinja2/environment.py", line 704, in _compile
    return compile(source, filename, "exec")  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jsmith/Desktop/temp/my-service/template/{% if shouldCreate %}file{% endif %}.jinja", line 15
    (% if shouldCreate %)
     ^
SyntaxError: f-string: invalid syntax
```

### Expected behavior

Import should work in conditional files.

### Operating system

macOS

### Operating system distribution and version

13.3.1

### Copier version

copier 7.2.0

### Python version

Python 3.10.4

### Installation method

pipx+pypi

**Comment by pawamoy** [comment] 2023-05-25 18:26
```
  File "/Users/jsmith/Desktop/temp/my-service/template/{% if shouldCreate %}file{% endif %}.jinja", line 15
    (% if shouldCreate %)
     ^
SyntaxError: f-string: invalid syntax
```

Looks like a typo?

**Comment by kielosz** [comment] 2023-05-25 20:00
> ```
>   File "/Users/jsmith/Desktop/temp/my-service/template/{% if shouldCreate %}file{% endif %}.jinja", line 15
>     (% if shouldCreate %)
>      ^
> SyntaxError: f-string: invalid syntax
> ```
> 
> 
>     
>   
> 
> Looks like a typo? Did you mean `{% if shouldCreate %}`?

Thank for the response. The name of the file is `{% if shouldCreate %}file{% endif %}.jinja`. When this file doesn't contain jinja import it works correctly. It only fails when I use the import statement inside.

**Comment by sisp** [comment] 2023-05-25 20:39
I'm able to reproduce the error. :+1:

**Comment by sisp** [comment] 2023-05-25 20:46
It doesn't fail when the file contains an include statement. It really happens only when there is an import statement in the file. :thinking:

**Comment by sisp** [comment] 2023-05-25 21:12
It might be an upstream bug in Jinja2. I can reproduce the problem with Jinja2 alone.

**Comment by sisp** [comment] 2023-05-26 10:30
It's an upstream bug caused by Jinja's code generation where generated code contains the templated filename in an f-string which leads to the error. I'll try to send a PR with a fix to the Jinja project, but it might have to wait until next week. If somebody would like to give it a try immediately, please let me know to avoid duplicate work.

In the meantime, the error should not occur if you use, e.g., brackets for Jinja templates, i.e. `[% if shouldCreate %]...[% endif %]` with a corresponding config in `copier.yml`.

**Comment by pawamoy** [comment] 2023-05-26 10:37
Could you link to the upstream issue if you found/created one? That would help us coordinate.

**Comment by sisp** [comment] 2023-05-26 12:43
As it turns out, an issue had already been created: https://github.com/pallets/jinja/issues/1792

I've submitted a PR that fixes it: https://github.com/pallets/jinja/pull/1852

**Comment by yajo** [comment] 2023-05-30 18:34
OK, let me close this issue, as it is not directly Copier's.

When there's a new fixed jinja release, we'll get it and bug gone.

**Closed** 2024-12-22 10:43 UTC
Labels: bug, triage
