### ISSUE TITLE
bug: copier should not create any files outside output directory

### ISSUE THREAD

**Issue by karolzlot** [copier-org/copier#431] opened 2021-07-21 08:09 UTC
**Describe the problem**

If I have directory named `{{ variable }}` and variable is not defined then copier will create some files or directories in `/` path which at best makes mess and and worst may cause system problems.

On Windows it means it creates files in `C:\` directory.

**Template**

As above

**To Reproduce**

As above

**Expected behavior**

Maybe should give error.

**Environment**
 - OS: Win10
 - Copier version: copier 5.1.0
 - Python version: Python 3.9.6
 - Installation method: pipx

**Additional context**

Example log (notice `\backend`):
```

    create  .dependabot\
    create  \backend\
    create  \backend\app\
    create  \backend\app\alembic\
    create  \backend\app\alembic\versions\
    create  \backend\app\api\
    create  \backend\app\api\api_v1\
    create  \backend\app\api\api_v1\routers\
    create  \backend\app\api\api_v1\routers\tests\
    create  \backend\app\api\dependencies\
    create  \backend\app\core\
    create  \backend\app\db\
    create  \backend\app\tests\
    create  \frontend\
    create  \frontend\public\
    create  \frontend\src\
    create  \frontend\src\admin\
    create  \frontend\src\admin\Users\
    create  \frontend\src\config\
    create  \frontend\src\utils\
    create  \frontend\src\views\
    create  \frontend\src\__tests__\
    create  \nginx\
    create  \scripts\
```

**Comment by Yajo** [comment] 2021-07-22 14:37
Duplicate of ##216

**Closed by Yajo** 2021-07-22 14:37 UTC
Labels: bug
