### ISSUE TITLE
feat: Support multiple templates in a single git repostory

### ISSUE THREAD

**Issue by WolverineFan** [copier-org/copier#1078] opened 2023-04-05 19:29 UTC
**Is your feature request related to a problem? Please describe.**
I would love to be able to put multiple templates in a single git repository.  Currently, when I reference a git URL to run Copier it only seems to find a `copier.yml` file in the root directory of the repo.  

**Describe the solution you'd like**
Ideally I would like to be able to reference a path to the template root from the command-line. Given a repo structure like this:
```
.
├── .git
├── template_1
│   ├── copier.yml
│   ├── file.txt
│   └── template.txt.jinja
├── template_2
│   ├── copier.yml
│   ├── dynamic.txt.jinja
│   └── static.txt
└── template_3
    ├── copier.yml
    ├── sample.yaml
    └── template.yaml.jinja
```

I can think of two common patterns that could work:
`copier --vcs-ref HEAD git@github.com:DeloitteHux/hux-k8s-cd-cdm-template.git//template_1 /path/to/render`
`copier --vcs-ref HEAD --template-root template_1 git@github.com:DeloitteHux/hux-k8s-cd-cdm-template.git /path/to/render`

**Describe alternatives you've considered**
Multiple repositories, which is fine to a degree, but there are use-cases where we want a single repo with multiple templates.

**Comment by yajo** [comment] 2023-04-06 05:12
This is answered in the docs: https://copier.readthedocs.io/en/latest/configuring/#subdirectory

Duplicate of #315

**Closed by yajo** 2023-04-06 05:12 UTC
Labels: enhancement
