### ISSUE TITLE
Don't run task on update

### ISSUE THREAD

**Issue by baurmatt** [copier-org/copier#238] opened 2020-07-29 14:45 UTC
Hey,

I'd like to have a task (`git init`) which is run on `copy` but not on `update`. Is this possible?

Thanks! :)

**Comment by pawamoy** [comment] 2020-07-29 15:17
Related to #196. In a more generic manner, it would be nice to have finer control over when a task is executed.

**Comment by pawamoy** [comment] 2020-07-29 15:23
Maybe the most straight-forward way to implement this functionality would be to set additional environment variables (or change the current ones) when executing tasks. Currently we just have `STAGE=task`. What about `STAGE=copy` and `STAGE=update` instead?

**Comment by baurmatt** [comment] 2020-07-29 15:26
I would suggestion not changing the `STAGE` environment variable as this would be a breaking change for existing users. Perhaps just implement a new environment variable `OPERATION` which can by `copy` or `update`?

**Comment by Yajo** [comment] 2020-08-11 08:20
Closing as duplicate of #240.

**Closed by Yajo** 2020-08-11 08:20 UTC
